steps:
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.dev.yaml
      - build

  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.dev.yaml
      - up