version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    # - ./src:/myfolder/src
    env_file:
      - ./.env.dev
    ports:
      - 8000:8080
  # mysql:
  #   image: mysql:8.0
  #   ports:
  #     - 3307:3306
  #   command:
  #     - --character-set-server=utf8mb4
  #     - --collation-server=utf8mb4_unicode_ci
  #   environment:
  #     - MYSQL_DATABASE=test1
  #     - MYSQL_ROOT_PASSWORD=1234
